
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class DefaultConfigData : Luban.BeanBase
{
    public DefaultConfigData(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Value = _buf.ReadInt();
    }

    public static DefaultConfigData DeserializeDefaultConfigData(ByteBuf _buf)
    {
        return new DefaultConfigData(_buf);
    }

    /// <summary>
    /// key
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// value
    /// </summary>
    public readonly int Value;
   
    public const int __ID__ = 787499789;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

