
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class EnemyData : Luban.BeanBase
{
    public EnemyData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Description = _buf.ReadString();
        Nameid = _buf.ReadString();
        Entityid = _buf.ReadInt();
        MaxHp = _buf.ReadFloat();
        Damage = _buf.ReadInt();
        TowerDamage = _buf.ReadFloat();
        ProjectileEntityid = _buf.ReadInt();
        ProjectileData = _buf.ReadInt();
        FireRate = _buf.ReadFloat();
        Range = _buf.ReadFloat();
        IsMultiAttack = _buf.ReadBool();
        Speed = _buf.ReadFloat();
        AddEnergy = _buf.ReadFloat();
        Type = _buf.ReadString();
    }

    public static EnemyData DeserializeEnemyData(ByteBuf _buf)
    {
        return new EnemyData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 敌人名字id
    /// </summary>
    public readonly string Nameid;
    /// <summary>
    /// 实体编号
    /// </summary>
    public readonly int Entityid;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly float MaxHp;
    /// <summary>
    /// 对基地的伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 对炮塔的伤害
    /// </summary>
    public readonly float TowerDamage;
    /// <summary>
    /// 炮弹实体编号
    /// </summary>
    public readonly int ProjectileEntityid;
    /// <summary>
    /// 炮弹数据
    /// </summary>
    public readonly int ProjectileData;
    /// <summary>
    /// 开火频率
    /// </summary>
    public readonly float FireRate;
    /// <summary>
    /// 范围
    /// </summary>
    public readonly float Range;
    /// <summary>
    /// 是否攻击多个敌人
    /// </summary>
    public readonly bool IsMultiAttack;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 玩家死亡时获得的能量
    /// </summary>
    public readonly float AddEnergy;
    /// <summary>
    /// 脚本
    /// </summary>
    public readonly string Type;
   
    public const int __ID__ = 953306930;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "description:" + Description + ","
        + "nameid:" + Nameid + ","
        + "Entityid:" + Entityid + ","
        + "MaxHp:" + MaxHp + ","
        + "Damage:" + Damage + ","
        + "TowerDamage:" + TowerDamage + ","
        + "ProjectileEntityid:" + ProjectileEntityid + ","
        + "ProjectileData:" + ProjectileData + ","
        + "FireRate:" + FireRate + ","
        + "Range:" + Range + ","
        + "IsMultiAttack:" + IsMultiAttack + ","
        + "Speed:" + Speed + ","
        + "AddEnergy:" + AddEnergy + ","
        + "Type:" + Type + ","
        + "}";
    }
}
}

