
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    [System.Flags]
    public enum EnumEntity
    {
        /// <summary>
        /// 启动场景
        /// </summary>
        GameStart = 101,
        /// <summary>
        /// 菜单场景
        /// </summary>
        Menu = 102,
        /// <summary>
        /// 第一关
        /// </summary>
        Level1 = 103,
        /// <summary>
        /// 第二关
        /// </summary>
        Level2 = 104,
        /// <summary>
        /// 第三关
        /// </summary>
        Level3 = 105,
        /// <summary>
        /// 第四关
        /// </summary>
        Level4 = 106,
        /// <summary>
        /// 第五关
        /// </summary>
        Level5 = 107,
        /// <summary>
        /// 主菜单
        /// </summary>
        UIMainMenuForm = 1001,
        /// <summary>
        /// 设置界面
        /// </summary>
        UIOptionsForm = 1002,
        /// <summary>
        /// 关卡选择界面
        /// </summary>
        UILevelSelectForm = 1003,
        /// <summary>
        /// 关卡主界面
        /// </summary>
        UILevelMainInfoForm = 1004,
        /// <summary>
        /// 炮塔列表
        /// </summary>
        UITowerListForm = 1005,
        /// <summary>
        /// 暂停界面
        /// </summary>
        UIPausePanelForm = 1006,
        /// <summary>
        /// 游戏结束
        /// </summary>
        UIGameOverForm = 1007,
        /// <summary>
        /// UI遮罩
        /// </summary>
        UIMask = 1008,
        /// <summary>
        /// 炮塔控制面板
        /// </summary>
        UITowerControllerForm = 1009,
        /// <summary>
        /// 下载速度界面
        /// </summary>
        UIDownloadForm = 1010,
        /// <summary>
        /// 突击加农炮弹
        /// </summary>
        MachineGunProjectile = 1040,
        /// <summary>
        /// 火箭炮弹
        /// </summary>
        RocketProjectile = 1041,
        /// <summary>
        /// 等离子喷枪炮弹
        /// </summary>
        LaserProjectile = 1042,
        /// <summary>
        /// 导弹炮弹
        /// </summary>
        SuperTowerProjectile = 1043,
        /// <summary>
        /// 子弹击中特效
        /// </summary>
        BulletHit = 1044,
        /// <summary>
        /// 激光击中特效
        /// </summary>
        LaserImpactPFX = 1045,
        /// <summary>
        /// 火箭尾部特效
        /// </summary>
        RocketTrail = 1046,
        /// <summary>
        /// 火箭爆炸特效
        /// </summary>
        RocketExplosionPfx = 1047,
        /// <summary>
        /// 导弹尾部特效
        /// </summary>
        SupertowerMissileTrail = 1048,
        /// <summary>
        /// 敌人死亡特效1
        /// </summary>
        SmallDeathExplosionPfx = 1049,
        /// <summary>
        /// 敌人死亡特效2
        /// </summary>
        BigDeathExplosionPfx = 1050,
        /// <summary>
        /// 敌人减速
        /// </summary>
        SlowFx = 1051,
        /// <summary>
        /// 血条
        /// </summary>
        HPBar = 1052,
        /// <summary>
        /// 敌人炮弹实体
        /// </summary>
        EnemyProjectile = 1053,
        /// <summary>
        /// 敌人攻击特效
        /// </summary>
        EnemyShootEffect = 1054,
        /// <summary>
        /// 炮塔爆炸
        /// </summary>
        TowerDeathExplosion = 1055,
        /// <summary>
        /// 关卡选择按钮
        /// </summary>
        LevelSelectionButton = 2001,
        /// <summary>
        /// 构建炮塔按钮
        /// </summary>
        TowerBuildButton = 2002,
        /// <summary>
        /// 突击加农炮预览
        /// </summary>
        AssaultCannonPreview = 3001,
        /// <summary>
        /// 火箭预览
        /// </summary>
        RocketPlatformPreview = 3002,
        /// <summary>
        /// 等离子喷枪预览
        /// </summary>
        PlasmaLancePreview = 3003,
        /// <summary>
        /// 能量塔预览
        /// </summary>
        EnergyPylonPreview = 3004,
        /// <summary>
        /// 电磁脉冲发生器预览
        /// </summary>
        EMPGeneratorPreview = 3005,
        /// <summary>
        /// 导弹阵列预览
        /// </summary>
        MissileArrayPreview = 3006,
        /// <summary>
        /// 突击加农炮
        /// </summary>
        AssaultCannon = 3007,
        /// <summary>
        /// 火箭
        /// </summary>
        RocketPlatform = 3008,
        /// <summary>
        /// 等离子喷枪
        /// </summary>
        PlasmaLance = 3009,
        /// <summary>
        /// 能量塔
        /// </summary>
        EnergyPylon = 3010,
        /// <summary>
        /// 电磁脉冲发生器
        /// </summary>
        EMPGenerator = 3011,
        /// <summary>
        /// 导弹阵列
        /// </summary>
        MissileArray = 3012,
        /// <summary>
        /// 突击加农炮等级1
        /// </summary>
        AssaultCannon_Level1 = 3013,
        /// <summary>
        /// 突击加农炮等级2
        /// </summary>
        AssaultCannon_Level2 = 3014,
        /// <summary>
        /// 突击加农炮等级3
        /// </summary>
        AssaultCannon_Level3 = 3015,
        /// <summary>
        /// 火箭等级1
        /// </summary>
        RocketPlatform_Level1 = 3016,
        /// <summary>
        /// 火箭等级2
        /// </summary>
        RocketPlatform_Level2 = 3017,
        /// <summary>
        /// 火箭等级3
        /// </summary>
        RocketPlatform_Level3 = 3018,
        /// <summary>
        /// 等离子喷枪等级1
        /// </summary>
        PlasmaLance_Level1 = 3019,
        /// <summary>
        /// 等离子喷枪等级2
        /// </summary>
        PlasmaLance_Level2 = 3020,
        /// <summary>
        /// 等离子喷枪等级3
        /// </summary>
        PlasmaLance_Level3 = 3021,
        /// <summary>
        /// 能量塔等级1
        /// </summary>
        EnergyPylon_Level1 = 3022,
        /// <summary>
        /// 能量塔等级2
        /// </summary>
        EnergyPylon_Level2 = 3023,
        /// <summary>
        /// 能量塔等级3
        /// </summary>
        EnergyPylon_Level3 = 3024,
        /// <summary>
        /// 电磁脉冲发生器等级1
        /// </summary>
        EMPGenerator_Level1 = 3025,
        /// <summary>
        /// 电磁脉冲发生器等级2
        /// </summary>
        EMPGenerator_Level2 = 3026,
        /// <summary>
        /// 电磁脉冲发生器等级3
        /// </summary>
        EMPGenerator_Level3 = 3027,
        /// <summary>
        /// 导弹阵列等级1
        /// </summary>
        MissileArray_Level1 = 3028,
        /// <summary>
        /// 范围指示器
        /// </summary>
        RadiusVisualiser = 3029,
        /// <summary>
        /// 炮塔放置特效
        /// </summary>
        BuildPfx = 3030,
        /// <summary>
        /// 虫子
        /// </summary>
        Hoverbuggy = 3031,
        /// <summary>
        /// 直升机
        /// </summary>
        Hovercopter = 3032,
        /// <summary>
        /// 坦克
        /// </summary>
        Hovertank = 3033,
        /// <summary>
        /// 首领
        /// </summary>
        Hoverboss = 3034,
        /// <summary>
        /// 超级虫子
        /// </summary>
        SuperHoverbuggy = 3035,
        /// <summary>
        /// 超级直升机
        /// </summary>
        SuperHovercopter = 3036,
        /// <summary>
        /// 超级坦克
        /// </summary>
        SuperHovertank = 3037,
        /// <summary>
        /// 超级首领
        /// </summary>
        SuperHoverboss = 3038,
        /// <summary>
        /// 玩家
        /// </summary>
        EntityPlayer = 3039,
    }

} 

