
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EnumSound
    {
        None = 0,
        GameBGM = 10001,
        MenuBGM = 10002,
        EnemyFire = 20001,
        MacrossPlacement = 20002,
        WeaponPlacement1 = 20003,
        WeaponPlacement2 = 20004,
        base_attack = 21001,
        zone_enter = 21002,
        EnemiesExploding1 = 22001,
        EnemiesExploding2 = 22002,
        EnemiesExploding3 = 22003,
        EnemiesExploding4 = 22004,
        EnemiesExploding5 = 22005,
        Destruction1 = 23001,
        Destruction2 = 23002,
        Destruction3 = 23003,
        Destruction4 = 23004,
        Destruction5 = 23005,
        LaserFire = 24001,
        MG1 = 25001,
        MG2 = 25002,
        MG3 = 25003,
        MG4 = 25004,
        MG5 = 25005,
        MG6 = 25006,
        MG7 = 25007,
        MG8 = 25008,
        MG9 = 25009,
        MG10 = 25010,
        MG11 = 25011,
        MG12 = 25012,
        MG13 = 25013,
        MG14 = 25014,
        RocketTowerShoot = 26001,
        SuperTowerShot1 = 27001,
        SuperTowerShot2 = 27002,
        SuperTowerShot3 = 27003,
        SuperTowerShot4 = 27004,
        SuperTowerShot5 = 27005,
        SuperTowerShot6 = 27006,
        SuperTowerShot7 = 27007,
        TDCurrency = 30001,
        TDDefeat = 30002,
        TDEMPIdle = 30003,
        TDTowerSell = 30004,
        TDTowerUpgrade = 30005,
        TDVictory = 30006,
        ui_sound_back = 30007,
        ui_sound_forward = 30008,
    }

} 

