
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EnumProjectile
    {
        None = 0,
        EntityProjectileHitscanLogic = 1,
        EntityProjectileBallisticLogic = 2,
        EntityEnergyPylonLogic = 3,
        EntityEMPGeneratorLogic = 4,
        EntityProjectileWobblingHomingLogic = 5,
    }

} 

