
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class LocalizationData : Luban.BeanBase
{
    public LocalizationData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Key = _buf.ReadString();
        Zh = _buf.ReadString();
        En = _buf.ReadString();
    }

    public static LocalizationData DeserializeLocalizationData(ByteBuf _buf)
    {
        return new LocalizationData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// key
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// zhvalue
    /// </summary>
    public readonly string Zh;
    /// <summary>
    /// envalue
    /// </summary>
    public readonly string En;
   
    public const int __ID__ = 395803139;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "key:" + Key + ","
        + "zh:" + Zh + ","
        + "en:" + En + ","
        + "}";
    }
}
}

