
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbDefaultConfigData
{
    private readonly System.Collections.Generic.Dictionary<string, DefaultConfigData> _dataMap;
    private readonly System.Collections.Generic.List<DefaultConfigData> _dataList;
    
    public TbDefaultConfigData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, DefaultConfigData>();
        _dataList = new System.Collections.Generic.List<DefaultConfigData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DefaultConfigData _v;
            _v = global::GameConfig.DefaultConfigData.DeserializeDefaultConfigData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, DefaultConfigData> DataMap => _dataMap;
    public System.Collections.Generic.List<DefaultConfigData> DataList => _dataList;

    public DefaultConfigData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DefaultConfigData Get(string key) => _dataMap[key];
    public DefaultConfigData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

