
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbEnemyData
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyData> _dataMap;
    private readonly System.Collections.Generic.List<EnemyData> _dataList;
    
    public TbEnemyData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyData>();
        _dataList = new System.Collections.Generic.List<EnemyData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EnemyData _v;
            _v = global::GameConfig.EnemyData.DeserializeEnemyData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EnemyData> DataMap => _dataMap;
    public System.Collections.Generic.List<EnemyData> DataList => _dataList;

    public EnemyData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EnemyData Get(int key) => _dataMap[key];
    public EnemyData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

