
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbLocalizationData
{
    private readonly System.Collections.Generic.Dictionary<int, LocalizationData> _dataMap;
    private readonly System.Collections.Generic.List<LocalizationData> _dataList;
    
    public TbLocalizationData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, LocalizationData>();
        _dataList = new System.Collections.Generic.List<LocalizationData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            LocalizationData _v;
            _v = global::GameConfig.LocalizationData.DeserializeLocalizationData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LocalizationData> DataMap => _dataMap;
    public System.Collections.Generic.List<LocalizationData> DataList => _dataList;

    public LocalizationData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LocalizationData Get(int key) => _dataMap[key];
    public LocalizationData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

