
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbProjectileData
{
    private readonly System.Collections.Generic.Dictionary<int, ProjectileData> _dataMap;
    private readonly System.Collections.Generic.List<ProjectileData> _dataList;
    
    public TbProjectileData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ProjectileData>();
        _dataList = new System.Collections.Generic.List<ProjectileData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ProjectileData _v;
            _v = global::GameConfig.ProjectileData.DeserializeProjectileData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ProjectileData> DataMap => _dataMap;
    public System.Collections.Generic.List<ProjectileData> DataList => _dataList;

    public ProjectileData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ProjectileData Get(int key) => _dataMap[key];
    public ProjectileData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

