
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbSceneData
{
    private readonly System.Collections.Generic.Dictionary<int, SceneData> _dataMap;
    private readonly System.Collections.Generic.List<SceneData> _dataList;
    
    public TbSceneData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SceneData>();
        _dataList = new System.Collections.Generic.List<SceneData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SceneData _v;
            _v = global::GameConfig.SceneData.DeserializeSceneData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SceneData> DataMap => _dataMap;
    public System.Collections.Generic.List<SceneData> DataList => _dataList;

    public SceneData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SceneData Get(int key) => _dataMap[key];
    public SceneData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

