
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbSceneConfig
{
    private readonly System.Collections.Generic.Dictionary<int, SceneConfig> _dataMap;
    private readonly System.Collections.Generic.List<SceneConfig> _dataList;
    
    public TbSceneConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SceneConfig>();
        _dataList = new System.Collections.Generic.List<SceneConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SceneConfig _v;
            _v = global::GameConfig.SceneConfig.DeserializeSceneConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SceneConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SceneConfig> DataList => _dataList;

    public SceneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SceneConfig Get(int key) => _dataMap[key];
    public SceneConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

