
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class WaveElementData : Luban.BeanBase
{
    public WaveElementData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Enemyid = _buf.ReadInt();
        SpawnTime = _buf.ReadFloat();
    }

    public static WaveElementData DeserializeWaveElementData(ByteBuf _buf)
    {
        return new WaveElementData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 敌人id
    /// </summary>
    public readonly int Enemyid;
    /// <summary>
    /// 获取怪物生成时间
    /// </summary>
    public readonly float SpawnTime;
   
    public const int __ID__ = -1549595667;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Enemyid:" + Enemyid + ","
        + "SpawnTime:" + SpawnTime + ","
        + "}";
    }
}
}

