
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class LevelData : Luban.BeanBase
{
    public LevelData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Description = _buf.ReadString();
        Name = _buf.ReadString();
        DescriptionId = _buf.ReadInt();
        SceneId = _buf.ReadInt();
        InitEnergy = _buf.ReadInt();
        PlayerPosition = global::GameConfig.vector3.Deserializevector3(_buf);
        PlayerQuaternion = global::GameConfig.vector3.Deserializevector3(_buf);
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);WaveIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); WaveIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AllowTowers = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AllowTowers.Add(_e0);}}
    }

    public static LevelData DeserializeLevelData(ByteBuf _buf)
    {
        return new LevelData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int DescriptionId;
    /// <summary>
    /// 场景Id
    /// </summary>
    public readonly int SceneId;
    /// <summary>
    /// 初始能量
    /// </summary>
    public readonly int InitEnergy;
    /// <summary>
    /// 玩家位置
    /// </summary>
    public readonly vector3 PlayerPosition;
    /// <summary>
    /// 玩家旋转
    /// </summary>
    public readonly vector3 PlayerQuaternion;
    /// <summary>
    /// 波次id
    /// </summary>
    public readonly System.Collections.Generic.List<int> WaveIds;
    /// <summary>
    /// 关卡允许使用的炮塔
    /// </summary>
    public readonly System.Collections.Generic.List<int> AllowTowers;
   
    public const int __ID__ = 347258158;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "description:" + Description + ","
        + "name:" + Name + ","
        + "DescriptionId:" + DescriptionId + ","
        + "SceneId:" + SceneId + ","
        + "InitEnergy:" + InitEnergy + ","
        + "PlayerPosition:" + PlayerPosition + ","
        + "PlayerQuaternion:" + PlayerQuaternion + ","
        + "WaveIds:" + Luban.StringUtil.CollectionToString(WaveIds) + ","
        + "AllowTowers:" + Luban.StringUtil.CollectionToString(AllowTowers) + ","
        + "}";
    }
}
}

