
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class ProjectileData : Luban.BeanBase
{
    public ProjectileData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Description = _buf.ReadString();
        Damage = _buf.ReadFloat();
        SplahDamage = _buf.ReadFloat();
        SplashRange = _buf.ReadFloat();
    }

    public static ProjectileData DeserializeProjectileData(ByteBuf _buf)
    {
        return new ProjectileData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly float Damage;
    /// <summary>
    /// 溅射伤害
    /// </summary>
    public readonly float SplahDamage;
    /// <summary>
    /// 溅射范围
    /// </summary>
    public readonly float SplashRange;
   
    public const int __ID__ = 37936467;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "description:" + Description + ","
        + "Damage:" + Damage + ","
        + "SplahDamage:" + SplahDamage + ","
        + "SplashRange:" + SplashRange + ","
        + "}";
    }
}
}

