
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class SceneConfig : Luban.BeanBase
{
    public SceneConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Level = _buf.ReadInt();
        Description = _buf.ReadString();
    }

    public static SceneConfig DeserializeSceneConfig(ByteBuf _buf)
    {
        return new SceneConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = 935827150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "level:" + Level + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

