
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{

/// <summary>
/// 所有对象继承必须继承该接口
/// 仅在加载数据时调用
/// <summary>
public interface IVOFun
{
	void _LoadData(ByteBuf _buf);
}

/// <summary>
/// 用于解析引用关系
/// <summary>
public interface IResolvable
{
    void ResolveRef(Tables tables);
}

public partial class Tables
{
    public TbAssetsPathData TbAssetsPathData {get; set;}
    public TbEnemyData TbEnemyData {get; set;}
    public TbLevelData TbLevelData {get; set;}
    public TbProjectileData TbProjectileData {get; set;}
    public TbSceneConfig TbSceneConfig {get; set;}
    public TbSceneData TbSceneData {get; set;}
    public TbTowerData TbTowerData {get; set;}
    public TbTowerLevelData TbTowerLevelData {get; set;}
    public TbWaveData TbWaveData {get; set;}
    public TbWaveElementData TbWaveElementData {get; set;}

    public Tables(){ }
}

}
