
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbTowerData : IVOFun, IResolvable
{
    private readonly System.Collections.Generic.Dictionary<int, TowerData> _dataMap;
    private readonly System.Collections.Generic.List<TowerData> _dataList;
    
    /*
    public TbTowerData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TowerData>();
        _dataList = new System.Collections.Generic.List<TowerData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TowerData _v;
            _v = global::GameConfig.TowerData.DeserializeTowerData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    */

    public TbTowerData()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TowerData>();
        _dataList = new System.Collections.Generic.List<TowerData>();
    }

    public System.Collections.Generic.Dictionary<int, TowerData> DataMap => _dataMap;
    public System.Collections.Generic.List<TowerData> DataList => _dataList;

    public TowerData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TowerData Get(int key) => _dataMap[key];
    public TowerData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }


    public void _LoadData(ByteBuf _buf)
    {
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TowerData _v;
            _v = global::GameConfig.TowerData.DeserializeTowerData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
}

}

