
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbTowerLevelData : IVOFun, IResolvable
{
    private readonly System.Collections.Generic.Dictionary<int, TowerLevelData> _dataMap;
    private readonly System.Collections.Generic.List<TowerLevelData> _dataList;
    
    /*
    public TbTowerLevelData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TowerLevelData>();
        _dataList = new System.Collections.Generic.List<TowerLevelData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TowerLevelData _v;
            _v = global::GameConfig.TowerLevelData.DeserializeTowerLevelData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    */

    public TbTowerLevelData()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TowerLevelData>();
        _dataList = new System.Collections.Generic.List<TowerLevelData>();
    }

    public System.Collections.Generic.Dictionary<int, TowerLevelData> DataMap => _dataMap;
    public System.Collections.Generic.List<TowerLevelData> DataList => _dataList;

    public TowerLevelData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TowerLevelData Get(int key) => _dataMap[key];
    public TowerLevelData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }


    public void _LoadData(ByteBuf _buf)
    {
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TowerLevelData _v;
            _v = global::GameConfig.TowerLevelData.DeserializeTowerLevelData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
}

}

