
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbWaveElementData : IVOFun, IResolvable
{
    private readonly System.Collections.Generic.Dictionary<int, WaveElementData> _dataMap;
    private readonly System.Collections.Generic.List<WaveElementData> _dataList;
    
    /*
    public TbWaveElementData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WaveElementData>();
        _dataList = new System.Collections.Generic.List<WaveElementData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WaveElementData _v;
            _v = global::GameConfig.WaveElementData.DeserializeWaveElementData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    */

    public TbWaveElementData()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WaveElementData>();
        _dataList = new System.Collections.Generic.List<WaveElementData>();
    }

    public System.Collections.Generic.Dictionary<int, WaveElementData> DataMap => _dataMap;
    public System.Collections.Generic.List<WaveElementData> DataList => _dataList;

    public WaveElementData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WaveElementData Get(int key) => _dataMap[key];
    public WaveElementData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }


    public void _LoadData(ByteBuf _buf)
    {
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WaveElementData _v;
            _v = global::GameConfig.WaveElementData.DeserializeWaveElementData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
}

}

