
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbWaveData : IVOFun, IResolvable
{
    private readonly System.Collections.Generic.Dictionary<int, WaveData> _dataMap;
    private readonly System.Collections.Generic.List<WaveData> _dataList;
    
    /*
    public TbWaveData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WaveData>();
        _dataList = new System.Collections.Generic.List<WaveData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WaveData _v;
            _v = global::GameConfig.WaveData.DeserializeWaveData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    */

    public TbWaveData()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WaveData>();
        _dataList = new System.Collections.Generic.List<WaveData>();
    }

    public System.Collections.Generic.Dictionary<int, WaveData> DataMap => _dataMap;
    public System.Collections.Generic.List<WaveData> DataList => _dataList;

    public WaveData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WaveData Get(int key) => _dataMap[key];
    public WaveData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }


    public void _LoadData(ByteBuf _buf)
    {
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WaveData _v;
            _v = global::GameConfig.WaveData.DeserializeWaveData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
}

}

