
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class TowerLevelData : Luban.BeanBase
{
    public TowerLevelData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Description = _buf.ReadString();
        NameId = _buf.ReadString();
        Desid = _buf.ReadString();
        UpgradeDesid = _buf.ReadString();
        Entityid = _buf.ReadInt();
        ProjectileData = _buf.ReadInt();
        FireRate = _buf.ReadFloat();
        Range = _buf.ReadFloat();
        SpeedDewnRate = _buf.ReadFloat();
        EnergyRaise = _buf.ReadFloat();
        EnergyRaiseRate = _buf.ReadFloat();
        BuildEnergy = _buf.ReadInt();
        SellEnergy = _buf.ReadInt();
    }

    public static TowerLevelData DeserializeTowerLevelData(ByteBuf _buf)
    {
        return new TowerLevelData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 炮塔Id
    /// </summary>
    public readonly string NameId;
    public readonly string Desid;
    /// <summary>
    /// 炮塔描述id
    /// </summary>
    public readonly string UpgradeDesid;
    /// <summary>
    /// 实体编号
    /// </summary>
    public readonly int Entityid;
    /// <summary>
    /// 炮弹数据
    /// </summary>
    public readonly int ProjectileData;
    /// <summary>
    /// 开火频率
    /// </summary>
    public readonly float FireRate;
    /// <summary>
    /// 范围
    /// </summary>
    public readonly float Range;
    /// <summary>
    /// 减速率
    /// </summary>
    public readonly float SpeedDewnRate;
    /// <summary>
    /// 生成能量
    /// </summary>
    public readonly float EnergyRaise;
    /// <summary>
    /// 生成能量
    /// </summary>
    public readonly float EnergyRaiseRate;
    /// <summary>
    /// 建造能量
    /// </summary>
    public readonly int BuildEnergy;
    /// <summary>
    /// 出售能量
    /// </summary>
    public readonly int SellEnergy;
   
    public const int __ID__ = -1228178331;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "description:" + Description + ","
        + "NameId:" + NameId + ","
        + "Desid:" + Desid + ","
        + "UpgradeDesid:" + UpgradeDesid + ","
        + "Entityid:" + Entityid + ","
        + "ProjectileData:" + ProjectileData + ","
        + "FireRate:" + FireRate + ","
        + "Range:" + Range + ","
        + "SpeedDewnRate:" + SpeedDewnRate + ","
        + "EnergyRaise:" + EnergyRaise + ","
        + "EnergyRaiseRate:" + EnergyRaiseRate + ","
        + "BuildEnergy:" + BuildEnergy + ","
        + "SellEnergy:" + SellEnergy + ","
        + "}";
    }
}
}

